//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationService.Core.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotificationService.Core.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;Product \&quot;{0}\&quot;(id: {1}) has been created&quot;.
        /// </summary>
        internal static string ProductCreatedEmailNotificationBodyFormat {
            get {
                return ResourceManager.GetString("ProductCreatedEmailNotificationBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCreated.
        /// </summary>
        internal static string ProductCreatedNotificationType {
            get {
                return ResourceManager.GetString("ProductCreatedNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your product with id {0} was removed.
        /// </summary>
        internal static string ProductDeletedEmailNotificationBodyFormat {
            get {
                return ResourceManager.GetString("ProductDeletedEmailNotificationBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductDeleted.
        /// </summary>
        internal static string ProductDeletedNotificationType {
            get {
                return ResourceManager.GetString("ProductDeletedNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your poduct &quot;{0}&quot; ({1}) was given to other user.
        /// </summary>
        internal static string YourProductWasGivenToOtherUserEmailBodyFormat {
            get {
                return ResourceManager.GetString("YourProductWasGivenToOtherUserEmailBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your product was given to other user.
        /// </summary>
        internal static string YourProductWasGivenToOtherUserSubject {
            get {
                return ResourceManager.GetString("YourProductWasGivenToOtherUserSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were given a product &quot;{0}&quot; ({1}).
        /// </summary>
        internal static string YouWereGivenAProductEmailBody {
            get {
                return ResourceManager.GetString("YouWereGivenAProductEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were given a product.
        /// </summary>
        internal static string YouWereGivenAProductSubject {
            get {
                return ResourceManager.GetString("YouWereGivenAProductSubject", resourceCulture);
            }
        }
    }
}
